### ISSUE TITLE
Bragg Peak Tab - Merge GSAS option from right click error

### ISSUE THREAD

**Issue by marshallmcdonnell** [neutrons/FastGR#80]

**Comment by marshallmcdonnell** [comment]
When I right-click a workspace in Bragg Peak Tab and select Merge GSAS, I get the following error:

'''
Traceback (most recent call last):
  File "/SNS/users/j35/git/FastGR_dev/fastgr/treelib.py", line 306, in do_merge_to_gss
    self._mainWindow.get_workflow.write_gss_file(ws_name_list=bank_ws_list, gss_file_name=new_gss_file_name)
AttributeError: 'function' object has no attribute 'write_gss_file'
'''

**Comment by marshallmcdonnell** [comment]
@wdzhou has this fixed in a pull request. Just need to fix other issues and then can merge.

**Comment by marshallmcdonnell** [comment]
Now, I get the following

```
Traceback (most recent call last):
  File "/SNS/users/ntm/software/fastgr/FastGR/build/lib/addie/treelib.py", line 306, in do_merge_to_gss
    self._mainWindow.get_workflow.write_gss_file(ws_name_list=bank_ws_list, gss_file_name=new_gss_file_name)
AttributeError: 'function' object has no attribute 'write_gss_file'
```

**Comment by marshallmcdonnell** [comment]
I was able to right-click but when I got to save, I get the following:
![Selection_575.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/582e0a126232920e00b26a35/125516c66e82c728ace21e0d46db9196268197a080e78016f308b2d86b56357c2301a03f32dfa17de7107e510e584ba4105b5840fff88d2ba6b43821885d08ffcd7f1d2598694ef1e1c84afd13b0328a488fb7b98a45c6eb3c25ee8e8e463f0c48.png)

**Comment by marshallmcdonnell** [comment]
For `master` commit [4b7c29e](https://github.com/neutrons/addie/commit/4b7c29eeb436fd68ba8a997139f80ec42379be61), get the following error when trying to save the test file GSAS_NaNO3_275C.gsa:
```
SaveGSS-[Notice] SaveGSS started
SaveGSS-[Error] SaveGSS: Failed to open file. Error was: No such file or directory in "('/home/ntm/tests/('/home/ntm/tests/GSAS_NaNO3_275C.gsa', 'GSAS File (*.gsa)')"
SaveGSS-[Error] Error in execution of algorithm SaveGSS:
SaveGSS-[Error] SaveGSS: error (see log)
Traceback (most recent call last):
  File "/home/ntm/direnv/python3/addie/build/lib/addie/treelib.py", line 310, in do_merge_to_gss
    self._mainWindow.get_workflow().write_gss_file(ws_name_list=bank_ws_list, gss_file_name=new_gss_file_name)
  File "/home/ntm/direnv/python3/addie/build/lib/addie/addiedriver.py", line 582, in write_gss_file
    Format='SLOG', Bank=1, Append=append_mode)
  File "/home/ntm/software/mantid/build-master/bin/mantid/simpleapi.py", line 1112, in algorithm_wrapper
    algm.execute()
RuntimeError: SaveGSS: error (see log)
```

Looks like there is a tuple on the `SaveGSS-[Error] SaveGSS: Failed to open file. Error was: No such file or directory in "('/home/ntm/tests/('/home/ntm/tests/GSAS_NaNO3_275C.gsa', 'GSAS File (*.gsa)')"` line instead of the filename only.
